### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by andreypopp** [jevakallio/react-derivable#1]
Hello,

I've built another React bindings for the excellent derivable library. It's called... React Reactive: https://github.com/andreypopp/react-reactive.

Why I'm creating this issue is I'm thinking of renaming mine to react-derivable and then publish to npm but as your library already exists (though not on npm) and derivable author already starred you repo and linked from some of the derivable issues I figured out I'd better ask you first if you are ok with that.

**Comment by andreypopp** [comment]
cc @jevakallio as you are not subscribed to the repo

**Comment by jevakallio** [comment]
I'm fine with it, will discuss with @ds300 so he can update relevant docs links and rename, likely tomorrow.

**Comment by ds300** [comment]
We discussed this last night and I'm also fine with it. I'll update the readme. Go ahead, @andreypopp !

**Comment by andreypopp** [comment]
Awesome, thank you.

**Comment by andreypopp** [comment]
Ok, it's up on npm. Thank you all.

**Comment by jevakallio** [comment]
Great! I've renamed this repository and added a link to your in the readme.
